### PR TITLE
Fix for base64 inlined images

### LINKED ISSUE #32: Breaks on inline base64 images in styles
Issue #28 fixes `:` bug due to the `background-image` property containing a `:` as per

```
background-image:url(http://foo.com)
```

In a similar class of bugs is an inline style containing a `;`

```
background-image:url(data:image/png;base64,iVBORw0KGgoAAA)
```

Since styles are split on `;` this breaks.

### PR DESCRIPTION
**Pull request by aleemb**
Fixes #32.

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ var camelCaseAttrMap = require('./camel-case-attribute-names');
 
 function createStyleJsonFromString(styleString) {
   styleString = styleString || '';
-  var styles = styleString.split(';');
+  var styles = styleString.split(/;(?!base64)/);
```
Comment (aleemb) [inline lib/utils.js]: This regex says to split on all `;` that don't `(?!` have the trailing string `base64)`

**Comment by aknuds1** [comment]
Thanks @aleemb!
